import { SigningClientResolver } from "../../../helper-func-types";
import { MsgSubmitProposal, MsgExecLegacyContent, MsgVote, MsgVoteWeighted, MsgDeposit, MsgUpdateParams, MsgCancelProposal } from "./tx";
export declare const createSubmitProposal: (clientResolver?: SigningClientResolver) => (signerAddress: string, message: MsgSubmitProposal, fee: import("../../../helper-func-types").StdFee | "auto", memo: string) => Promise<import("../../../helper-func-types").DeliverTxResponse>;
export declare const createExecLegacyContent: (clientResolver?: SigningClientResolver) => (signerAddress: string, message: MsgExecLegacyContent, fee: import("../../../helper-func-types").StdFee | "auto", memo: string) => Promise<import("../../../helper-func-types").DeliverTxResponse>;
export declare const createVote: (clientResolver?: SigningClientResolver) => (signerAddress: string, message: MsgVote, fee: import("../../../helper-func-types").StdFee | "auto", memo: string) => Promise<import("../../../helper-func-types").DeliverTxResponse>;
export declare const createVoteWeighted: (clientResolver?: SigningClientResolver) => (signerAddress: string, message: MsgVoteWeighted, fee: import("../../../helper-func-types").StdFee | "auto", memo: string) => Promise<import("../../../helper-func-types").DeliverTxResponse>;
export declare const createDeposit: (clientResolver?: SigningClientResolver) => (signerAddress: string, message: MsgDeposit, fee: import("../../../helper-func-types").StdFee | "auto", memo: string) => Promise<import("../../../helper-func-types").DeliverTxResponse>;
export declare const createUpdateParams: (clientResolver?: SigningClientResolver) => (signerAddress: string, message: MsgUpdateParams, fee: import("../../../helper-func-types").StdFee | "auto", memo: string) => Promise<import("../../../helper-func-types").DeliverTxResponse>;
export declare const createCancelProposal: (clientResolver?: SigningClientResolver) => (signerAddress: string, message: MsgCancelProposal, fee: import("../../../helper-func-types").StdFee | "auto", memo: string) => Promise<import("../../../helper-func-types").DeliverTxResponse>;
