/**
* This file and any referenced files were automatically generated by @cosmology/telescope@1.10.11
* DO NOT MODIFY BY HAND. Instead, download the latest proto files for your chain
* and run the transpile command or npm scripts command that is used to regenerate this bundle.
*/
import { HttpEndpoint } from "@interchainjs/types";
import { Rpc } from "./helpers";
export declare const getRpcEndpointKey: (rpcEndpoint: string | HttpEndpoint) => string;
export declare const getRpcClient: (rpcEndpoint: string | HttpEndpoint) => Promise<Rpc>;
export declare const createRpcClient: (rpcEndpoint: string | HttpEndpoint) => Promise<import("@interchainjs/types").TxRpc>;
