name: xpla
version: v1.8.0

chains:
  - id: dimension_37-1
    name: xpla
    image: nowooj/xpla:v1.8.0-rc0
    numValidators: 1
    ports:
      rest: 1317
      rpc: 26657
      faucet: 8007
      evm-http-jsonrpc: 8545

  - id: cosmoshub-4
    name: cosmoshub
    numValidators: 1
    ports:
      rest: 1313
      rpc: 26653
      faucet: 8003

relayers:
  - name: xpla-cosmos
    type: hermes
    replicas: 1
    chains:
      - dimension_37-1
      - cosmoshub-4

explorer:
  enabled: true
  ports:
    rest: 8080

registry:
  enabled: true
  ports:
    rest: 8081