name: xpla
version: v1.8.0

chains:
  - id: dimension_37-1
    name: xpla
    image: ghcr.io/hyperweb-io/starship/xpla:v1.8.0-rc0
    numValidators: 1
    ports:
      rest: 1317
      rpc: 26657
      faucet: 8007

  - id: cosmoshub-4
    name: cosmoshub
    numValidators: 1
    ports:
      rest: 1313
      rpc: 26653
      faucet: 8003

relayers:
  - name: xpla-cosmos
    image: ghcr.io/hyperweb-io/starship/hermes:1.13.1
    type: hermes
    replicas: 1
    chains:
      - dimension_37-1
      - cosmoshub-4
    config:
      mode:
       packets:
          clear_interval: 10000
      event_source:
        mode: "pull"
explorer:
  enabled: true
  ports:
    rest: 8080

registry:
  enabled: true
  ports:
    rest: 8081