packages:
  - 'contracts'
  - 'libs/*'
  - 'networks/*'

catalog:
  '@chain-registry/types': '^2.0.138'
  '@cosmjs/stargate': '^0.38.1'
  '@cosmjs/tendermint-rpc': '^0.38.1'
  '@interchainjs/auth': '^1.21.0'
  '@interchainjs/amino': '^1.21.0'
  '@interchainjs/cosmos': '^1.21.0'
  '@interchainjs/cosmos-types': '^1.21.0'
  '@interchainjs/crypto': '^1.21.0'
  '@interchainjs/encoding': '^1.20.0'
  '@interchainjs/ethereum': '^1.21.0'
  '@interchainjs/math': '^1.20.0'
  '@interchainjs/pubkey': '^1.21.0'
  '@interchainjs/types': '^1.21.0'
  '@interchainjs/utils': '^1.21.0'
  '@types/node': '^22'
  'interchainjs': '^1.21.0'
  'lerna': '^9.0.3'
  'typescript': '^5.9.3'
  'tsdown': '^0.21.0-beta.2'
  'vitest': '^4.0.17'
