/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Bech32I",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Bech32I__factory>;
    getContractFactory(
      name: "DistributionI",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DistributionI__factory>;
    getContractFactory(
      name: "IAuth",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAuth__factory>;
    getContractFactory(
      name: "IBank",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IBank__factory>;
    getContractFactory(
      name: "IGov",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IGov__factory>;
    getContractFactory(
      name: "ISlashing",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISlashing__factory>;
    getContractFactory(
      name: "IWasm",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IWasm__factory>;
    getContractFactory(
      name: "StakingI",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.StakingI__factory>;

    getContractAt(
      name: "Bech32I",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Bech32I>;
    getContractAt(
      name: "DistributionI",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DistributionI>;
    getContractAt(
      name: "IAuth",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAuth>;
    getContractAt(
      name: "IBank",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IBank>;
    getContractAt(
      name: "IGov",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IGov>;
    getContractAt(
      name: "ISlashing",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ISlashing>;
    getContractAt(
      name: "IWasm",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IWasm>;
    getContractAt(
      name: "StakingI",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.StakingI>;

    deployContract(
      name: "Bech32I",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Bech32I>;
    deployContract(
      name: "DistributionI",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DistributionI>;
    deployContract(
      name: "IAuth",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAuth>;
    deployContract(
      name: "IBank",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBank>;
    deployContract(
      name: "IGov",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IGov>;
    deployContract(
      name: "ISlashing",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISlashing>;
    deployContract(
      name: "IWasm",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IWasm>;
    deployContract(
      name: "StakingI",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.StakingI>;

    deployContract(
      name: "Bech32I",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Bech32I>;
    deployContract(
      name: "DistributionI",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DistributionI>;
    deployContract(
      name: "IAuth",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAuth>;
    deployContract(
      name: "IBank",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBank>;
    deployContract(
      name: "IGov",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IGov>;
    deployContract(
      name: "ISlashing",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISlashing>;
    deployContract(
      name: "IWasm",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IWasm>;
    deployContract(
      name: "StakingI",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.StakingI>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
