/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export type EquivocationStruct = {
  height: BigNumberish;
  time: BigNumberish;
  power: BigNumberish;
  consensusAddress: string;
};

export type EquivocationStructOutput = [
  height: bigint,
  time: bigint,
  power: bigint,
  consensusAddress: string
] & { height: bigint; time: bigint; power: bigint; consensusAddress: string };

export type PageRequestStruct = {
  key: BytesLike;
  offset: BigNumberish;
  limit: BigNumberish;
  countTotal: boolean;
  reverse: boolean;
};

export type PageRequestStructOutput = [
  key: string,
  offset: bigint,
  limit: bigint,
  countTotal: boolean,
  reverse: boolean
] & {
  key: string;
  offset: bigint;
  limit: bigint;
  countTotal: boolean;
  reverse: boolean;
};

export type PageResponseStruct = { nextKey: BytesLike; total: BigNumberish };

export type PageResponseStructOutput = [nextKey: string, total: bigint] & {
  nextKey: string;
  total: bigint;
};

export interface EvidenceInterface extends Interface {
  getFunction(
    nameOrSignature: "evidence" | "getAllEvidence" | "submitEvidence"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "SubmitEvidence"): EventFragment;

  encodeFunctionData(functionFragment: "evidence", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getAllEvidence",
    values: [PageRequestStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "submitEvidence",
    values: [EquivocationStruct]
  ): string;

  decodeFunctionResult(functionFragment: "evidence", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitEvidence",
    data: BytesLike
  ): Result;
}

export namespace SubmitEvidenceEvent {
  export type InputTuple = [submitter: AddressLike, hash: BytesLike];
  export type OutputTuple = [submitter: string, hash: string];
  export interface OutputObject {
    submitter: string;
    hash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Evidence extends BaseContract {
  connect(runner?: ContractRunner | null): Evidence;
  waitForDeployment(): Promise<this>;

  interface: EvidenceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  evidence: TypedContractMethod<
    [evidenceHash: BytesLike],
    [EquivocationStructOutput],
    "view"
  >;

  getAllEvidence: TypedContractMethod<
    [pageRequest: PageRequestStruct],
    [
      [EquivocationStructOutput[], PageResponseStructOutput] & {
        evidence: EquivocationStructOutput[];
        pageResponse: PageResponseStructOutput;
      }
    ],
    "view"
  >;

  submitEvidence: TypedContractMethod<
    [evidence: EquivocationStruct],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "evidence"
  ): TypedContractMethod<
    [evidenceHash: BytesLike],
    [EquivocationStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllEvidence"
  ): TypedContractMethod<
    [pageRequest: PageRequestStruct],
    [
      [EquivocationStructOutput[], PageResponseStructOutput] & {
        evidence: EquivocationStructOutput[];
        pageResponse: PageResponseStructOutput;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitEvidence"
  ): TypedContractMethod<
    [evidence: EquivocationStruct],
    [boolean],
    "nonpayable"
  >;

  getEvent(
    key: "SubmitEvidence"
  ): TypedContractEvent<
    SubmitEvidenceEvent.InputTuple,
    SubmitEvidenceEvent.OutputTuple,
    SubmitEvidenceEvent.OutputObject
  >;

  filters: {
    "SubmitEvidence(address,bytes)": TypedContractEvent<
      SubmitEvidenceEvent.InputTuple,
      SubmitEvidenceEvent.OutputTuple,
      SubmitEvidenceEvent.OutputObject
    >;
    SubmitEvidence: TypedContractEvent<
      SubmitEvidenceEvent.InputTuple,
      SubmitEvidenceEvent.OutputTuple,
      SubmitEvidenceEvent.OutputObject
    >;
  };
}
